name: templete
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_platform_widgets: ^6.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
